// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boltgrpc.proto

/*
Package boltgrpc is a generated protocol buffer package.

It is generated from these files:
	boltgrpc.proto

It has these top-level messages:
	UpdateRequest
	ViewRequest
	UpdateResponse
	ViewResponse
*/
package boltgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateResponse_Error int32

const (
	UpdateResponse_NONE   UpdateResponse_Error = 0
	UpdateResponse_FAILED UpdateResponse_Error = 1
)

var UpdateResponse_Error_name = map[int32]string{
	0: "NONE",
	1: "FAILED",
}
var UpdateResponse_Error_value = map[string]int32{
	"NONE":   0,
	"FAILED": 1,
}

func (x UpdateResponse_Error) String() string {
	return proto.EnumName(UpdateResponse_Error_name, int32(x))
}
func (UpdateResponse_Error) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ViewResponse_Error int32

const (
	ViewResponse_NONE   ViewResponse_Error = 0
	ViewResponse_FAILED ViewResponse_Error = 1
)

var ViewResponse_Error_name = map[int32]string{
	0: "NONE",
	1: "FAILED",
}
var ViewResponse_Error_value = map[string]int32{
	"NONE":   0,
	"FAILED": 1,
}

func (x ViewResponse_Error) String() string {
	return proto.EnumName(ViewResponse_Error_name, int32(x))
}
func (ViewResponse_Error) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type UpdateRequest struct {
	Buckets []string `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	Key     []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Val     []byte   `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateRequest) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *UpdateRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *UpdateRequest) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type ViewRequest struct {
	Buckets []string `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	Key     []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *ViewRequest) Reset()                    { *m = ViewRequest{} }
func (m *ViewRequest) String() string            { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()               {}
func (*ViewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ViewRequest) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ViewRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type UpdateResponse struct {
	Err UpdateResponse_Error `protobuf:"varint,1,opt,name=err,enum=boltgrpc.UpdateResponse_Error" json:"err,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateResponse) GetErr() UpdateResponse_Error {
	if m != nil {
		return m.Err
	}
	return UpdateResponse_NONE
}

type ViewResponse struct {
	Val []byte             `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Err ViewResponse_Error `protobuf:"varint,2,opt,name=err,enum=boltgrpc.ViewResponse_Error" json:"err,omitempty"`
}

func (m *ViewResponse) Reset()                    { *m = ViewResponse{} }
func (m *ViewResponse) String() string            { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()               {}
func (*ViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ViewResponse) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *ViewResponse) GetErr() ViewResponse_Error {
	if m != nil {
		return m.Err
	}
	return ViewResponse_NONE
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "boltgrpc.UpdateRequest")
	proto.RegisterType((*ViewRequest)(nil), "boltgrpc.ViewRequest")
	proto.RegisterType((*UpdateResponse)(nil), "boltgrpc.UpdateResponse")
	proto.RegisterType((*ViewResponse)(nil), "boltgrpc.ViewResponse")
	proto.RegisterEnum("boltgrpc.UpdateResponse_Error", UpdateResponse_Error_name, UpdateResponse_Error_value)
	proto.RegisterEnum("boltgrpc.ViewResponse_Error", ViewResponse_Error_name, ViewResponse_Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bolt service

type BoltClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error)
}

type boltClient struct {
	cc *grpc.ClientConn
}

func NewBoltClient(cc *grpc.ClientConn) BoltClient {
	return &boltClient{cc}
}

func (c *boltClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/boltgrpc.Bolt/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltClient) View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := grpc.Invoke(ctx, "/boltgrpc.Bolt/View", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bolt service

type BoltServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	View(context.Context, *ViewRequest) (*ViewResponse, error)
}

func RegisterBoltServer(s *grpc.Server, srv BoltServer) {
	s.RegisterService(&_Bolt_serviceDesc, srv)
}

func _Bolt_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltgrpc.Bolt/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bolt_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boltgrpc.Bolt/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltServer).View(ctx, req.(*ViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bolt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boltgrpc.Bolt",
	HandlerType: (*BoltServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Bolt_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _Bolt_View_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "boltgrpc.proto",
}

func init() { proto.RegisterFile("boltgrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xca, 0xcf, 0x29,
	0x49, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x7c,
	0xb9, 0x78, 0x43, 0x0b, 0x52, 0x12, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x24, 0xb8, 0xd8, 0x93, 0x4a, 0x93, 0xb3, 0x53, 0x4b, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38,
	0x83, 0x60, 0x5c, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e,
	0x20, 0x10, 0x13, 0x24, 0x52, 0x96, 0x98, 0x23, 0xc1, 0x0c, 0x11, 0x29, 0x4b, 0xcc, 0x51, 0xb2,
	0xe4, 0xe2, 0x0e, 0xcb, 0x4c, 0x2d, 0x27, 0xc3, 0x30, 0xa5, 0x44, 0x2e, 0x3e, 0x98, 0x4b, 0x8a,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x0c, 0xb8, 0x98, 0x53, 0x8b, 0x8a, 0x24, 0x18, 0x15, 0x18,
	0x35, 0xf8, 0x8c, 0xe4, 0xf4, 0xe0, 0x7e, 0x40, 0x55, 0xa6, 0xe7, 0x5a, 0x54, 0x94, 0x5f, 0x14,
	0x04, 0x52, 0xaa, 0x24, 0xcb, 0xc5, 0x0a, 0xe6, 0x09, 0x71, 0x70, 0xb1, 0xf8, 0xf9, 0xfb, 0xb9,
	0x0a, 0x30, 0x08, 0x71, 0x71, 0xb1, 0xb9, 0x39, 0x7a, 0xfa, 0xb8, 0xba, 0x08, 0x30, 0x2a, 0xe5,
	0x73, 0xf1, 0x40, 0x5c, 0x07, 0xb5, 0x00, 0xea, 0x7e, 0x46, 0xb8, 0xfb, 0x85, 0xf4, 0x20, 0x56,
	0x32, 0x81, 0xad, 0x94, 0x41, 0x58, 0x89, 0xac, 0x8d, 0x78, 0x0b, 0x8d, 0xea, 0xb8, 0x58, 0x9c,
	0xf2, 0x73, 0x4a, 0x84, 0x6c, 0xb9, 0xd8, 0x20, 0x8e, 0x16, 0x12, 0xc7, 0xf4, 0x06, 0x38, 0xa8,
	0xa4, 0x24, 0x70, 0xf9, 0x4f, 0x89, 0x41, 0xc8, 0x9c, 0x8b, 0x05, 0xe4, 0x00, 0x21, 0x51, 0x74,
	0x07, 0x41, 0xb4, 0x8a, 0x61, 0x77, 0xa7, 0x12, 0x43, 0x12, 0x1b, 0x38, 0xba, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0x24, 0x64, 0xb3, 0x00, 0x02, 0x00, 0x00,
}
